### ISSUE TITLE
Question: "Which of the following configuration systems/API …" is not usable on certain window sizes

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#1]
Especially on Smartphones this Question is not usable.

Sending out a survey that is not compatible with mobile devices in this age would look rather unprofessional.

**Comment by sirblackheart** [comment]
> And I had a bug when restarting the browser, even selected options above were not available below. (pressing again on the choice helped, so its a really minor issue)

Reloading the page resets the selections for me. Disabling javascript shows a big red warning in lime survey, but shows all possible answers.

**Comment by markus2330** [comment]
Going back works, too.

**Comment by sirblackheart** [comment]
I can not reproduce this in Chromium 51. I can not even go back with the browser history. If you go normally back trough the survey back then your old selections should be still there, if not out survey would be completely broken.

**Comment by sirblackheart** [comment]
The question is now completely hidden if there is no possible answer option.

**Comment by markus2330** [comment]
Already noticed, nicely done.
