### ISSUE TITLE
Some parts are not updated

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#14]
unfortunately the history was not copied from previous repo, so I cannot refer to specific commits, but some feedback (I think its what @omnidan said he had done)

So somebody has to through all parts and check if everything is up-to-date.
(Please close other issues, if you fix them by doing so)

**Comment by markus2330** [comment]
@sirblackheart can you check everything as discussed (much) earlier?

**Comment by sirblackheart** [comment]
There where only three commits at elektra_abgaben after i copied the stuff here:

> commit 21c647f7d54a98840092e645333f3c370cca7026
> Author: Markus Raab <elektra@markus-raab.org>
> Date:   Wed Jun 1 14:08:18 2016 +0200
> 
>     move survey out of repo
> 
> commit 842729de708fa05d7f3d50817b1e9eaf45b9c048
> Author: Markus Raab <elektra@markus-raab.org>
> Date:   Wed Jun 1 11:59:11 2016 +0200
> 
>     add feedback
> 
> commit 54b4a4d5f765d1cb7cd7630928476f99f2938dc6
> Author: Markus Raab <elektra@markus-raab.org>
> Date:   Wed Jun 1 11:46:50 2016 +0200
> 
>     todo
> 
>

**Comment by sirblackheart** [comment]
> @sirblackheart can you check everything as discussed (much) earlier?

I do not understand the reference.

**Comment by markus2330** [comment]
The reference was to an e-mail I send a while ago.

The question is, if every change of questions.txt is now implemented. You can simply compare the latest version (not on per-commit basis)

**Comment by sirblackheart** [comment]
Well i only understand only now what the issue is about. I misunderstood it as missing parts from git history copied to this repo…

**Comment by sirblackheart** [comment]
I tried to be as thoroughly as possible, and questions.txt and limesurvey should no be in sync.

**Comment by markus2330** [comment]
Thank you, well done!

**Comment by sirblackheart** [comment]
But not all changes in lime survey are in questions.txt, i will update it.

**Comment by markus2330** [comment]
This can be done later, lets focus on getting the survey done.
