### ISSUE TITLE
donation should be single choice

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#17]
"I would like the following Organiation to recieve 0.20 €cent: " misspelled

**Comment by markus2330** [comment]
The problem is that the current selection does not feature links. Libreoffice/Debian/Arch/many others is the same donation (SPI). I doubt that many people know that.

**Comment by sirblackheart** [comment]
Ok, now i understand. So we have to switch to a radiobox answer.

**Comment by sirblackheart** [comment]
@markus2330  updated it.

**Comment by markus2330** [comment]
Please directly include the image, not load it from foreign domain.

**Comment by sirblackheart** [comment]
@markus2330 then we also have to do that for the smileys... where do i upload stuff in lime survey?
Do you think wikimedia is such a bad choice for a foreign domain?

**Comment by markus2330** [comment]
The smileys are certainly more problematic. Would be good to have no such issue at all, however.

Textual fixes are more important though.

**Comment by sirblackheart** [comment]
text is fixed, we will not be able to not use an external source of images. a solution would be to host them ourself? but not sure if that is much better then from wikimedia or similar. I will close this specific issue. If we want to do something about the image location, lets open a specific ticket after the pilot.
