### ISSUE TITLE
add smileys

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#18]
use 5 smileys, as discussed

(thumbs up and something very negativ/confusing)

**Comment by sirblackheart** [comment]
Personally i would favor some unicode emoticons in contrast to this animated ones. But animated one surely can give a better impression of an emotion.

- https://github.com/twitter/twemoji
- http://emojione.com/

**Comment by markus2330** [comment]
Yes, people liked the animated ones.

**Comment by sirblackheart** [comment]
Well it adds some trash factor to the whole survey, but fine.

**Comment by markus2330** [comment]
I only say how people responded. We can also use the non-animated ones and see how it works.

**Comment by markus2330** [comment]
(But we should not change something that got positive feedback without very careful consideration)

**Comment by Namoshek** [comment]
Final decision?

**Comment by markus2330** [comment]
Add some more smileys and let us find out in the pilot which are useful.

**Comment by markus2330** [comment]
@Namoshek can you create a small poll here? (give some smileys a number, and we write here what we like)

**Comment by Namoshek** [comment]
1) ![Happy Hopping](http://www.pic4ever.com/images/Just_Cuz_13.gif) `http://www.pic4ever.com/images/Just_Cuz_13.gif`
2) ![Thumbs-Up](http://yoursmiles.org/msmile/pozitive/m1212.gif) `http://yoursmiles.org/msmile/pozitive/m1212.gif`
3) ![Number One](http://yoursmiles.org/msmile/pozitive/m1236.gif) `http://yoursmiles.org/msmile/pozitive/m1236.gif`
4) ![Shoutout](http://yoursmiles.org/msmile/pozitive/m1207.gif) `http://yoursmiles.org/msmile/pozitive/m1207.gif`
5) ![Jumping Joy](http://yoursmiles.org/msmile/fun/m0111.gif) `http://yoursmiles.org/msmile/fun/m0111.gif`

6) ![Double Thumbs-Up](http://yoursmiles.org/msmile/fun/m0122.gif) `http://yoursmiles.org/msmile/fun/m0122.gif`
7) ![Confusing tripple?](http://www.pic4ever.com/images/ugly_confused2.gif) `http://www.pic4ever.com/images/ugly_confused2.gif`
8) ![Weird look](http://yoursmiles.org/tsmile/emb/t1827.gif) `http://yoursmiles.org/tsmile/emb/t1827.gif`
9) ![Big Yeys](http://yoursmiles.org/msmile/wonder/m1802.gif) `http://yoursmiles.org/msmile/wonder/m1802.gif`
10) ![Anger](http://yoursmiles.org/tsmile/agressive/t0111.gif) `http://yoursmiles.org/tsmile/agressive/t0111.gif`

11) ![Much Anger](http://yoursmiles.org/tsmile/agressive/t0105.gif) `http://yoursmiles.org/tsmile/agressive/t0105.gif`
12) ![Red Anger](http://yoursmiles.org/tsmile/agressive/t0172.gif) `http://yoursmiles.org/tsmile/agressive/t0172.gif`
13) ![Denial](http://yoursmiles.org/tsmile/no/t2638.gif) `http://yoursmiles.org/tsmile/no/t2638.gif`
14) ![Embarrased Denial](http://yoursmiles.org/tsmile/no/t2623.gif) `http://yoursmiles.org/tsmile/no/t2623.gif`
15) ![Help](http://yoursmiles.org/tsmile/fear/t3611.gif) `http://yoursmiles.org/tsmile/fear/t3611.gif`

**Comment by markus2330** [comment]
I like 3,1,2,5,6
10,14,16
17 also good (for do not care in the middle)

**Comment by sirblackheart** [comment]
like 1
meh 9 (my favored)
nogo 13

> neutral/"do not care" 17
yes, that is probably the best suited for that

**Comment by Namoshek** [comment]
Should we also add "can't really tell, because this stuff is way too confusing" (or in short: confusing)?

**Comment by markus2330** [comment]
Yes, confusing was desired, but 7 is strange.

**Comment by Namoshek** [comment]
I would probably use 15 for confusion.
My favorites as set would be:
![](http://yoursmiles.org/msmile/fun/m0122.gif) ![](http://www.pic4ever.com/images/kaffeetrinker_2.gif) ![](http://yoursmiles.org/tsmile/fear/t3611.gif) ![](http://yoursmiles.org/msmile/wonder/m1802.gif) ![](http://yoursmiles.org/tsmile/no/t2623.gif)

**Comment by markus2330** [comment]
Ok, looks fine to me.

**Comment by sirblackheart** [comment]
Ok @Namoshek are you adding them, should I?

**Comment by Namoshek** [comment]
I'll do it, sorry, was busy.

**Comment by Namoshek** [comment]
Do you agree with the order from bad to good (left to right)?

**Comment by markus2330** [comment]
yes, we should not differ here to other questions.

**Comment by Namoshek** [comment]
Good, then it should be fine.
