### ISSUE TITLE
Confusing Question: "Have you also contributed or used the configuration …"

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#2]
Feedback:
> - I didn't understand this question at all (as don't seem to be FLOSS 
> projects or waht FLOSS projects are you talking about here) - but maybe 
> it will make sense for the experts: "Have you also contributed or used 
> the configuration API/system of these FLOSS projects?" 

sugestion from Markus:

> evt. Erklärung was configuration API/system.. Ist?

**Comment by omnidan** [comment]
updated in limesurvey
