### ISSUE TITLE
Have "other" field for matrix

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#22]
What are our options to provide a textfield for the matrix questions?

**Comment by Namoshek** [comment]
I don't see any option for that except adding a follow-up question, but making it look like they belong together will be tough.

**Comment by markus2330** [comment]
It would be especially important for the very last question, so please try there first.

**Comment by markus2330** [comment]
Any progress here? Would be good to have it for one question

**Comment by Namoshek** [comment]
I thought about it again and even with an own question, I'm not sure how we could make it work properly.
I read something about a solution where you can create two new questions (one for the textfield, one for the radio buttons), hide them by JS and add them to the grid (basically move the HTML element), but that means without JS it will make absolutely no sense at all...

**Comment by markus2330** [comment]
9fbec268ecdea0ba84a2313b6b26af87a5753a12
What do you think about that hint instead?

**Comment by Namoshek** [comment]
Sounds like an idea. If someone really thinks something is important, he will certainly do that. But providing a simple textbox (in form of a follow-up question) should be no problem, only the same format (textbox + importance rating) is not possible.

**Comment by markus2330** [comment]
Then its better to simply have the note as in9fbec26. Adding more textboxes will be confusing (also for us)

**Comment by Namoshek** [comment]
Added it as hint to the question, so it is on the bottom (after all the answer possibilities), I think that is the point where it is the most helpful. If we write it with the question, it is probably already forgotton at after filling out all answers. Close if its ok.
