### ISSUE TITLE
Next/back button also on top of page

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#23]
Is this viable?

**Comment by Namoshek** [comment]
Do we want our participants to be able to skip whole pages (without reading)? I guess not, so the next-button seems not to be a good idea. But the back-button could be interesting, although I doubt that many people will go back in the survey.

**Comment by markus2330** [comment]
People might want to browse through the whole survey (especially because we do not give progress bar). I am also not sure if it should be used, but if we try it, then for the pilot.

**Comment by Namoshek** [comment]
I can re-add the progress bar, it was an accident that I deleted it for the whole survey (days ago already). I thought I would delete it for the welcome page only, because I don't like it there.

**Comment by markus2330** [comment]
There was positive feedback about not having a progress bar for only few pages.

We could say in the beginning how many pages there are.

**Comment by markus2330** [comment]
Please close if there is no easy way to add prev/next at top

**Comment by sirblackheart** [comment]
i suggest we take another look after the pilot, as it requires to edit the template and css and that will take some time to learn, but also should enable us to upload images.

**Comment by markus2330** [comment]
I am against making such changes after the pilot.

It is ok if we dont have it.

**Comment by Namoshek** [comment]
I tried adding it, but the problem is that it has to be inside the form element that is not part of the template we can edit, so the only way to add these buttons would be through JS anyway. I'm afraid this will be messy, so I'm against it.
