### ISSUE TITLE
In which remote configuration scenarios are you interested? 

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#24]
should be MC? (already use) as "other" option.

**Comment by omnidan** [comment]
It's MC now and I updated the question and answers.

> Was meint ihr dazu, dass ich "(e.g. through a web interface)" angehängt habe? Ich denke dann kann man sich mehr darunter vorstellen (es ist ja z.B. nicht remote configuration über ssh)

**Comment by markus2330** [comment]
it seems to be not updated in questions.txt

**Comment by omnidan** [comment]
Oh, I only updated the answers and not the question. Fixed that in 24fe5b836495e980ecd256ad7f2de14e21e5334b

**Comment by markus2330** [comment]
I would not use () after ?

What about adding through a web interface as one possible answer?

you really should update the first two answers, its unclear what it means.

**Comment by markus2330** [comment]
maybe even add ssh as alternative?

**Comment by markus2330** [comment]
"from one" sounds quite german

**Comment by omnidan** [comment]
Sorry for the late response and thanks for the feedback! I have updated the question and answers: https://github.com/sirblackheart/elektrasurvey/commit/62d6e079c6ffdcf46024a8d4c40b211b0c773fe2

Now some of the answers are a little long, but it's much clearer what they mean. If the question is fine now I'll change it on limesurvey too.

**Comment by markus2330** [comment]
"through one interface" seems obvious (why mention it?)

multiple devices with independent configurations
is still not so clear, do you mean:
changing settings on many devices w/o influencing unrelated settings

**Comment by markus2330** [comment]
Maybe you mean something completely different, its not really clear

**Comment by omnidan** [comment]
@markus2330 I just mean multiple devices, with each device having its own configuration (as a contrast to configuring a cluster, where you would have one configuration for multiple devices). Although I'm not sure how to state this more clearly than `multiple devices with independent/separate configurations`.

**Comment by omnidan** [comment]
Maybe just use `multiple devices, with each device having its own configuration` for the answer? Would that be better?

**Comment by markus2330** [comment]
Dont you think everyone will say yes here?

Maybe saying "non-cluster" would already help.

**Comment by omnidan** [comment]
@markus2330 updated to `non-clustered devices with independent configurations`. I think after reading the previous answer the contrast should be clear now.

**Comment by markus2330** [comment]
yes, its better now, you can update survey

**Comment by omnidan** [comment]
done!
