### ISSUE TITLE
donation in responses

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#26]
What happens if someone does not enter a valid e-mail address, does the response still get the default selection of lime-survey?

Would be good to have this right from begin with to not have too much post-processing.

**Comment by sirblackheart** [comment]
It probably does. But i expected, that we can filter this from the results, don't we?

**Comment by sirblackheart** [comment]
+ you can not continue without a valid email adress

**Comment by markus2330** [comment]
Of course we can. Maybe we need to do anyway (for the fully filled-out cirteria)

What do you mean with "you can not continue without a valid email adress"?

**Comment by sirblackheart** [comment]
![peek 2016-06-01 19-13](https://cloud.githubusercontent.com/assets/1131371/15718739/04829fce-282d-11e6-8bfa-33fc59462ba9.gif)

**Comment by markus2330** [comment]
I think the behaviour is ok, what is the use case for allowing wrong e-mail addresses?

**Comment by sirblackheart** [comment]
No i think it is ok, but it means we get either a donation selection with a valid e-mail adress or a donation selection an empty email adress so we can distinguish easily between both. In addition we probably should send every valid entered address a mail with thank you for supporting a donation for project bla, so we can cut away additional invalid email addresses.

**Comment by markus2330** [comment]
yes, good idea.

**Comment by markus2330** [comment]
But I think we also should include some preliminary results to not spam the people
