### ISSUE TITLE
include images directly in the survey

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#27]
(not important ticket)

**Comment by Namoshek** [comment]
What images are we talking about?

**Comment by markus2330** [comment]
the smileys and the link-symbol in donation question

**Comment by sirblackheart** [comment]
This will be fixed once #43 is decided

**Comment by sirblackheart** [comment]
all svg are now part of the template, please post here if you still find any external images

**Comment by markus2330** [comment]
Thank you!
