### ISSUE TITLE
Reevaluate the possibility to shorten grid answers so they only take one line

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#28]
This would probably be easier to the eye.

**Comment by Namoshek** [comment]
It is possible to set a size (in %) for the first column where the text is. Something about 30%+ looks good and solves the multi-line issue, but of course this can be different on different sized screens (talking about 1080p here)!

**Comment by sirblackheart** [comment]
> but of course this can be different on different sized screens

That is true. Hm maybe giving hints a slightly other style (slightly smaller, or some grey) would help.

**Comment by sirblackheart** [comment]
So i used <small> on most () parts. What do you think?

**Comment by Namoshek** [comment]
Sounds great

**Comment by markus2330** [comment]
I also like it. (except the one about remote stuff which is after ?, but thats a different issue)

**Comment by sirblackheart** [comment]
Well there are two questions with a note text near a ? I think it looks better with the text in braces after the question mark then having it in front of it.

**Comment by markus2330** [comment]
Ok, but it should be consistent. Can you update `API (e.g. Elektra):` then?

8879788afc50b3d470fb1c8b4b7d02471f790b86
Or do you think we should have an exception there?

**Comment by sirblackheart** [comment]
No i overlooked it, thank you for noticing.
