### ISSUE TITLE
other should not be exclusive in MC

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#29]
Allow MC to always fill out Other: so that people always can add stuff they have in their mind.

**Comment by Namoshek** [comment]
I think you are talking about exclusive options forbidding to fill out other?

**Comment by markus2330** [comment]
Yes! We want to have:
"I do not because: (use other to write why)"
so, other: should be still allowed.

This would be a nice workaround for the single text field issue.

**Comment by Namoshek** [comment]
So we should change (remove) the exclusive option for all questions?

**Comment by markus2330** [comment]
Actually, it can be exclusive, except for the "other" (if this is possible)
For the exclusive, we have the hline problem, however.

and only in the questions where it says as referenced in c0a70950edda73069a9ace392c2ac07abc54c8e4

**Comment by markus2330** [comment]
I am not so happy with "use next line" though...

**Comment by Namoshek** [comment]
Unfortunately it is not possible to exclude some answers from the exclusive-disable list...

**Comment by markus2330** [comment]
ok, then disable the feature completely. Then we know which survey responses can be filtered out.

**Comment by markus2330** [comment]
there are still some places see #33

**Comment by Namoshek** [comment]
Had to do something else lately, sorry. I went through the survey and deleted the exclusive option for all questions with "(use other to write why)". Please check if it's ok and close if so.
