### ISSUE TITLE
1st why ques: remove 'I did not'  

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#3]
Feedback
> - 1st why ques: remove 'I did not' and replace with 'no opinion' or 
> similar, otherwise confusing given the 'used or would use' framing of 
> the question 

Suggestion from Markus:

> Sollte verbessert werden.

**Comment by omnidan** [comment]
Habs im survey mal auf "I would not (use other to write why)" geändert, aber sollten wir das vllt in der Description schreiben? Man kann ja nur entweder das, oder Other auswählen?

**Comment by markus2330** [comment]
Yes, I forgot about logical exclusions in this functionality. Is it possible to always allow other?

**Comment by omnidan** [comment]
@markus2330 I just checked and actually it is possible to select "I would not" and "Other" at the same time.

**Comment by markus2330** [comment]
it works at least for your question (but not for all others). I will create a new task for this.

**Comment by markus2330** [comment]
see #29

**Comment by omnidan** [comment]
@markus2330 You're right, I tested it with the active survey and it seems to work with every question there. In the inactive up-to-date survey, it is exclusive.

**Comment by markus2330** [comment]
We only talk about the inactive survey here, the other is only for archival purposes.

**Comment by omnidan** [comment]
updated in limesurvey
