### ISSUE TITLE
e-mail should be optional

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#30]
Again we have lost any reference that submitting the e-mail address is optional.

Please add a <small>(optional)</small> or as note.

**Comment by sirblackheart** [comment]
is it ok this way?

**Comment by markus2330** [comment]
I would change
"Optional to enable a donation:"
to
Optional, but needed to enable a donation:

**Comment by markus2330** [comment]
Or avoid the sentence in the beginning but change

You can only select a donation, when you entered your e-mail address.

to 

Optional, but you can only select a donation if you entered your e-mail address.

**Comment by markus2330** [comment]
(I also changed comma and when -> if)
