### ISSUE TITLE
Send out survey

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#32]
@sirblackheart Can you send out the survey after it is finished to our internal mailing list?
(please refer to this repo for issues)

I will send it to the others.

**Comment by sirblackheart** [comment]
Internal mailing list is arbeiten@libelektra.org right?

**Comment by markus2330** [comment]
yes, I only wanted to avoid to put the e-mail address in a public repo ;)

**Comment by markus2330** [comment]
So is this a yes?

**Comment by sirblackheart** [comment]
yes

**Comment by sirblackheart** [comment]
We need to activate the survey so we get the link i think.

**Comment by sirblackheart** [comment]
So a last call out if anything should still be changed before the Pilot @Namoshek @omnidan @markus2330

**Comment by markus2330** [comment]
I think we are done, it looks great..

**Comment by Namoshek** [comment]
PLEASE MAKE A COPY BEFORE DOING SO!

**Comment by markus2330** [comment]
@Namoshek can you activate it?

**Comment by Namoshek** [comment]
I can.

**Comment by markus2330** [comment]
ok, please post link to use here

**Comment by Namoshek** [comment]
http://elektra.limequery.org/index.php/967282?lang=en

**Comment by sirblackheart** [comment]
@Namoshek made a copy

**Comment by markus2330** [comment]
Thank you, please also do a backup into this repo while you are on it.

**Comment by Namoshek** [comment]
I also made a copy, hehe. But no problem, two are better. :)

**Comment by markus2330** [comment]
http://elektra.limequery.org/index.php/967282
should be fine, too?

**Comment by markus2330** [comment]
or are there some hidden language feature that might translate parts of it?

**Comment by Namoshek** [comment]
Don't think so, default language is set to EN ofc.

**Comment by Namoshek** [comment]
Hint: Some scripts will not work in the backups, so for the final release we will have to fix them. But not today anymore.

**Comment by markus2330** [comment]
Please create a new issue for this

**Comment by sirblackheart** [comment]
sent

**Comment by markus2330** [comment]
I also sent them
