### ISSUE TITLE
Answer twice

### ISSUE THREAD

**Issue by KurtMi** [sirblackheart/elektrasurvey#35]
In the qeustion:
```
Finally, which benefits do you think are essential in order to add a dependency to a configuration system/library/API? (e.g. Elektra)
```
The answer:
```
must be well-maintained (bugs are fixed promptly)
```
is twice.

**Comment by markus2330** [comment]
Thank you! Do you think there should be a stronger or weaker form of well-maintained? (In a previous version we had "must not have any bugs")

**Comment by KurtMi** [comment]
Maybe add a second, weaker answer and a reformulation of the first one to something like: willing to implement new features on request.

**Comment by sirblackheart** [comment]
Fixed in `625192`.
Thank you for the suggestions.
The question is if we really want additional answer possibilities.

**Comment by Namoshek** [comment]
Approved. I also changed the width of the first column, so that there is not used more than 2 lines per row. Looks cleaner and a bit less now. Nothing to be really reviewed, though.

**Comment by markus2330** [comment]
Please keep issues open. We should cross-check to avoid regressions for other issues.
