### ISSUE TITLE
Survey Questions: Some suggestions

### ISSUE THREAD

**Issue by sanssecours** [sirblackheart/elektrasurvey#36]
The following text lists some suggestions regarding the questions of the survey. Please keep in mind, that these are only suggestions. Overall I would say the survey turned out nicely.

# General

Instead of the choice

> slightly important

maybe something like

> not very important

would make more sense.

# Page 1

> If you leave us your contact data, we will notify you and a donation will be paid.

I think “notify” makes only sense here, if we specify the topic of the notification. How about the following:

> If you leave us your contact data, we will notify you **about the turnout of the survey** and a donation will be paid.

?

# Page 2

## What is your experience with the following configuration systems/libraries/APIs?

While I think the smilies look cute, I am not really sure about their meaning. My guess would be (from left to right):

1. Don't know
2. Heard something about that somewhere
3. Too complicated
4. Boring, but easy to use
5. I really like that stuff

Is that correct?

## Have you also contributed to or used the configuration system/library/API in your FLOSS projects? 

> - introduce a new configuration file format (e.g. a new INI dialect)
> - introduce a new configuration system/library/API
> - implement a configuration file parser

I think we should use past time here:

> - introduce**d** a new configuration file format (e.g. a new INI dialect)
> - introduce**d** a new configuration system/library/API
> - implement**ed** a configuration file parser

---

> - my contributions were non-configurable

Maybe it would make sense to add **all** or **some** here, i.e.:

> - **all** my contributions were non-configurable

or 

> - **some of** my contributions were non-configurable

# Page 4

## Which effort do you think is worthwhile for providing better configuration experience?

> - provide proper default values

Since all the other choices use progressive tense, it makes sense to use it here too:

> - provid**ing** proper default values

---

> reading configuration of other applications

Probably better:

> reading configuration **values from** other applications

## In which remote configuration scenarios would you be interested?

> - through a web interface
> - through ssh

Maybe better:

> - **configuration via** a web interface
> - **configuration via** ssh

# Page 5

The following

> …40 €cent… 

should maybe be written as

> € 0.4

instead.

---

> will be sponsored to one organisation of your choice of the following

Maybe better:

> will be donated to one of the following organisations of your choice

# Page 6

The sentence

> We think configuration systems are a relevant part of free and open source software and expect to gather important data through this survey that not only helps our research but also gives other similar projects statistical data to base future decisions on.

is quite long. Maybe this would be better:

> We think configuration systems are a relevant part of free and open source software**. We** expect to gather important data through this survey that not only helps our research**,** but also gives other similar projects statistical data to base future decisions on.

**Comment by markus2330** [comment]
> slightly important

This was taken from the Likert scala, so we better leave it.

> about the turnout of the survey

#37

> meaning of smileys

there is an hint when you hover the smileys

> tenses

#38

> all vs. some

#39

> providing

done in 9bbfb7a3525c0065de67c1e7fab69b5ab24aa164

> reading configuration values from other applications

done in 008782579fbd3da08fc0833f3b6d97716d37b664

> 40 €cent

Is untypical, but does it bother? (was not my idea, but it looks ok)

> shorten sentence

#41

**Comment by markus2330** [comment]
Thank you, very good Feedback! Further discussions please in individual issues.

**Comment by sanssecours** [comment]
>> 40 €cent

> Is untypical, but does it bother? (was not my idea, but it looks ok)

Not really. At first glance it does look like we donate €40 instead of €0.4 though.

**Comment by sirblackheart** [comment]
>>> 40 €cent

>> Is untypical, but does it bother? (was not my idea, but it looks ok)

> Not really. At first glance it does look like we donate €40 instead of €0.4 though.

The idea was to avoid the `0,40` vs `0.40` problematic by assuming that cent is is known on an international level.

**Comment by Namoshek** [comment]
To be honest, I find the wording "40 €cent" also a bit strange. I agree that "cent" alone is probably not enough of information, because it could be any currency, but it can be confusing. The positive aspect of it is though, that it makes the amount we donate per money look more. That's why I also dislike 0,40 or 0.40 as wording...

**Comment by sirblackheart** [comment]
` -,40 €`

` 0,40 €`

` 0.40 €`

` € 40ct`

**Comment by markus2330** [comment]
`€ 40 cent`

**Comment by Namoshek** [comment]
I like `€ 40ct` and `€ 40 cent`, but it also comes down to the look and readability in the text I guess.

**Comment by sirblackheart** [comment]
relevantes Feedback:
> Bei Contact & Feedback, ist es noetig da "€cent" statt cent zu schreiben? das "cent" koennte evtl ueberlesen werden und zwischen 40€ und 40cent ist doch ein Unterschied.

You both are right er probably should go for `€ 40 cent` or `€ 40ct`

**Comment by markus2330** [comment]
Does everyone know the abbreviation `ct`?

**Comment by sirblackheart** [comment]
cent is probably more international

**Comment by sirblackheart** [comment]
updated in: `invite.md`, `front` text and `email` form text
also update `200€` to `€ 200`

**Comment by markus2330** [comment]
Thank you!
