### ISSUE TITLE
tenses

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#38]
introduce a new configuration file format (e.g. a new INI dialect)
        introduce a new configuration system/library/API
        implement a configuration file parser

**Comment by sirblackheart** [comment]
updated in `625192`

**Comment by Namoshek** [comment]
Approved

**Comment by markus2330** [comment]
Please keep open, label review done is enough. We should cross-check in final survey.

**Comment by markus2330** [comment]
Looks fine!
