### ISSUE TITLE
my contributions were non-configurable

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#39]
>        all my contributions were non-configurable

or

>        some of my contributions were non-configurable

I would say "all"

**Comment by sirblackheart** [comment]
"all" or "most"

**Comment by Namoshek** [comment]
Most

**Comment by markus2330** [comment]
Ok, most but with "some" you should click somewhere else

**Comment by sirblackheart** [comment]
updated in `625192`

**Comment by Namoshek** [comment]
Approved
