### ISSUE TITLE
shorten sentence: We think configuration systems are..

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#41]
The sentence

>    We think configuration systems are a relevant part of free and open source software and expect to gather important data through this survey that not only helps our research but also gives other similar projects statistical data to base future decisions on.

is quite long. Maybe this would be better:

>   We think configuration systems are a relevant part of free and open source software. We expect to gather important data through this survey that not only helps our research, but also gives other similar projects statistical data to base future decisions on.

**Comment by omnidan** [comment]
In the meantime this text has changed a lot, can this be closed?

**Comment by markus2330** [comment]
What do you mean? It is still very similar (its on the finishing page):

We think configuration systems are a relevant part of free and open source software. We expect to gather important data through this survey that not only helps our research, but also gives other similar projects statistical data to base future decisions on.

**Comment by omnidan** [comment]
@markus2330 Oh, I didn't realize it's on the page after submitting the survey. Seems to be updated then.

**Comment by markus2330** [comment]
Last page also looks fine to me.
