### ISSUE TITLE
more donation information at the beginning

### ISSUE THREAD

**Issue by omnidan** [sirblackheart/elektrasurvey#42]
From an email:

> Bei der Information am Anfang steht "a donation will be paid.", aber
es ist unklar an wen und wieviel. Ich würde normalerweise schon am
Anfang mehr dazu wissen wollen.

**Comment by markus2330** [comment]
> Wenn die Donation deswegen da ist um die Leute zu motivieren, würde ich schon am Anfang sagen, dass es die gibt und für wen. Ich würd es bestimmt eher ausfüllen, wenn ich das Gefühl hab, es dient auch einem guten Zweck.

**Comment by sirblackheart** [comment]
Yes we probably should also have the information on the starting page, as it is also possible for someone to get to the survey trough a shared link.
Changed it.

**Comment by markus2330** [comment]
Looks good!
