### ISSUE TITLE
some smileys are unclear

### ISSUE THREAD

**Issue by omnidan** [sirblackheart/elektrasurvey#43]
From an email:

> Frage: What is your experience with the following configuration
systems/libraries/APIs?
> Die Smileys sind für mich nicht eindeutig verständlich - zB ist der
Smiley mit Kaffee laut ALT Text "neutral", ich hätte aber eher an
"langsam" oder "umständlich" gedacht.

**Comment by sirblackheart** [comment]
Ich wiederhole hier nochmal den Vorschlag farbige Emoticons aus dem Unicode Zeichensatz zu nehmen.
Begründung: Wir können Smileys wählen deren Emotion ziemlich klar definiert ist und fast jeder kennt ihr Bedeutung durch die starke Verbreitung in Messengern am Smartphone.

**Comment by markus2330** [comment]
Kannst du konkrete Vorschläge hier pasten?

**Comment by omnidan** [comment]
Es gibt z.B.:

 * disappointed: 😞 
 * cry: :cry:
 * smile: :smile:
 * neutral face: 😐

**Comment by sirblackheart** [comment]
![1f61e](https://cloud.githubusercontent.com/assets/1131371/15746609/8f39f022-28d7-11e6-8a2e-30dfd7d7f33c.png) disappointed

![1f612](https://cloud.githubusercontent.com/assets/1131371/15746638/b2f2aafe-28d7-11e6-95f7-4eff5a0acbe3.png) meh

![1f636](https://cloud.githubusercontent.com/assets/1131371/15746660/c70a404c-28d7-11e6-99af-73fcb9c67036.png) neutral

![1f642](https://cloud.githubusercontent.com/assets/1131371/15746648/bd6a895c-28d7-11e6-8d6e-5e9b72ac5fa1.png) i like it 

![1f60d](https://cloud.githubusercontent.com/assets/1131371/15746685/ddba0854-28d7-11e6-9443-1d5e6543f2d6.png) i love it

________

oder wenn man es verniedlichen will

![1f63f](https://cloud.githubusercontent.com/assets/1131371/15746700/ed077648-28d7-11e6-9b10-4654e92be70f.png) disapointed 

![1f63e](https://cloud.githubusercontent.com/assets/1131371/15746716/fa3ab348-28d7-11e6-955d-777781a882bd.png) meh 

![1f408](https://cloud.githubusercontent.com/assets/1131371/15746792/44e690ec-28d8-11e6-9528-2fa168f480a5.png) neutral

![1f63a](https://cloud.githubusercontent.com/assets/1131371/15746727/0216eeba-28d8-11e6-8b69-dee2964b5cc1.png) i like it

![1f63b](https://cloud.githubusercontent.com/assets/1131371/15746741/0de71396-28d8-11e6-8b39-e65af9efd530.png) i love it

**Comment by markus2330** [comment]
Yes, the non-cat ones might be better than what we have now.

**Comment by sirblackheart** [comment]
you can take a look at them in survey#experiments. I included a likert scale below them.
The downside of using this specific 5 emoticons in combination with a likert scale is that we loose emotions like confused.

I also do not know why the do not appear centered above the radioboxes.

**Comment by sirblackheart** [comment]
Hm i also just noticed that the likert scale i used could be rather confusing as it could be interpreted as knowledge experience this way.
But the likert scale examples all seem to lack emotions.

**Comment by sirblackheart** [comment]
Alternative suggestion:

> What is your experience with the following configuration systems/libraries/APIs?

- very frustrating
- slightly frustrating
- neutral
- enjoyable
- loved it

**Comment by sirblackheart** [comment]
What about replacing no answer with neutral. How important is it for us to distinguish between those two? How bad is it if a user looses the possibility not to answer for having a neutral answer instead?
On the other hand we could assume that if something is confusing and irritating it also is frustrating to use?

**Comment by markus2330** [comment]
Neutral and "no answer" might be something completely different.

**Comment by sirblackheart** [comment]
Feedback
> Skeptisch den Smileys gegenüber bei "What is your experience with the following configuration systems/lirbaries/APIs?" - kommt mir außerdem so vor, als wuerde da nicht alle moeglichen Statements abgedeckt werden dadurch.

Würd heißen wir sollten dann doch mehr Emotionen abdecken?

**Comment by markus2330** [comment]
Hast du ein Einfall für eine Skala von 7 smileys in Unicode?

**Comment by sirblackheart** [comment]
eine 7er skala wird sicher nicht leicht mit Emotionen (ist traurig oder wütend schlechter?), dann sollten wir uns vielleicht eine alternative Möglichkeit zur Auswahl überlegen.

**Comment by sirblackheart** [comment]
![1f621](https://cloud.githubusercontent.com/assets/1131371/15788895/eb5e3550-29c9-11e6-893c-876639b19c22.png)
![1f634](https://cloud.githubusercontent.com/assets/1131371/15788900/ef9dfd12-29c9-11e6-82ca-cd399dca1e59.png)
![1f622](https://cloud.githubusercontent.com/assets/1131371/15788904/f5e39f2e-29c9-11e6-91de-410da0581c85.png)

![1f624](https://cloud.githubusercontent.com/assets/1131371/15788911/fd26056a-29c9-11e6-9575-a2d6bc28d3a3.png)

![1f611](https://cloud.githubusercontent.com/assets/1131371/15788915/041df256-29ca-11e6-8dbf-6842572b557a.png)
![1f644](https://cloud.githubusercontent.com/assets/1131371/15788923/0a982552-29ca-11e6-93c4-3d1f79f85e1d.png)

**Comment by markus2330** [comment]
Can you write next to it what the ALT text would be?

**Comment by sirblackheart** [comment]
on `experiments` preview the survey, select an answer (other than no answer and had not used) for  `getenv` in the  

> Which configuration systems/libraries/APIs have you already used or would like to use in one of your projects?

question.

You get a preview of a possible multi-choice expirence question.

**Comment by markus2330** [comment]
I had no image for "very frustrating" in the survey preview?

Yes, with random smileys, we would only have a nominal scale.

The disappointed -> i love it would be easier to handle. And it would cover nearly every situation.

**Comment by Namoshek** [comment]
Yes, very frustrating is not shown in the survey currently, but I think it looks good and there is also more than enough space for the smileys.

**Comment by sirblackheart** [comment]
So what is the decision then for 625192?

**Comment by markus2330** [comment]
What are the latest opinions?

I think a 5er scale with disappointed to I love it, as above, is best.

**Comment by sirblackheart** [comment]
updated in `625192`

**Comment by sirblackheart** [comment]
@Namoshek the question nuber has changed, in ref to #34

**Comment by Namoshek** [comment]
Concerning what? Is anything to be changed?

**Comment by sirblackheart** [comment]
The experience question, i deleted the existing `usedsystems2` and imported the one from `experimental` so the question got a new number. I just thought i should mention it because of id script relation.

**Comment by Namoshek** [comment]
Ah, well, only if there is a (custom) script somewhere related to the question. I don't think we changed anything there? I myself did only create (and fix) the script for "add project" and "to last page", I guess. The other ones seem to still work fine.

**Comment by sirblackheart** [comment]
Yes i think everything using question code and relevance equation should be fine as long as we do not change question codes.

**Comment by sirblackheart** [comment]
Please review if the smileys are working

**Comment by Namoshek** [comment]
I changed the ALT-texts of the two frustrating emotes as they were inconsistent with the texts below the smileys. Images are shown properly and the smiley choice makes sense regarding the suggested meaning (texts). It's fine from my side!

**Comment by markus2330** [comment]
Thank you! Smileys work perfectly now!
