### ISSUE TITLE
Should all questions be optional?

### ISSUE THREAD

**Issue by omnidan** [sirblackheart/elektrasurvey#45]
From an email:

> Ich kann mich durch die gesamte Umfrage klicken und sie am Schluss
abschicken, ohne irgendetwas ausgefüllt zu haben - ist das Absicht?

**Comment by markus2330** [comment]
I think its good this way. I hope we can distuingish real answers with click-throughs afterwards. So lets keep this ticket open.

**Comment by markus2330** [comment]
Someone said:

> Na ein bisschen verleitet es schon zum weiterklicken, wenn man nicht gleich weiß, was man antworten soll.

**Comment by sirblackheart** [comment]
I think we should keep it that way but rather give more hints based on the feedback we get.
Basically try to avoid people not knowing what to select.

**Comment by sirblackheart** [comment]
As there has been no objection i am closing this.

**Comment by markus2330** [comment]
Did we add all hints based on the feedback?

**Comment by sirblackheart** [comment]
no but those should be separate issues, this one is about keeping the possibility of click-throughs. Hint addition currently is basedon feedback to specific questions.
