### ISSUE TITLE
add progress bar

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#47]
> bei der Umfrage wär’s glaub ich gut, wenn irgendwo eine Indikation dafür ist, wie viel die Person noch ausfüllen muss.

Is it possible to give an indiciator without the front page?

**Comment by Namoshek** [comment]
We might be able to put it somewhere else in the template, I'll have a look tomorrow.

**Comment by markus2330** [comment]
Maybe make indication visible all the time? Here some feedback from an expert:

> Ja, das habe ich auch öfter als Feedback bekommen. Die Teilnehmer möchten
> gerne eine Art Orientierung haben wie lange es dauert. Ich habe es z.B.
> einmal nicht eingeblendet gehabt und viele der Teilnehmer sind mir auf der
> letzten Seiten ausgestiegen, weil sie dachten es geht noch länger so
> weiter. Wenn man einen Balken hat können sie es besser einschätzen und
> bleiben dann vielleicht bis zum Schluss, weil sie dann vielleicht denken,
> die eine Seite mache ich auch noch fertig.

**Comment by Namoshek** [comment]
I agree that it makes sense. The problem is that the progress bar just divides the 100% by the number of pages, so welcome- and finish-page are part of the progress as well. The different number of questions per page (and it is quite different for Why? and How?) also has negative impact on the real progress.

I'll add it back and we will have a look, I guess.

**Comment by Namoshek** [comment]
Done. I was wrong about the first and last page or maybe we changed some settings in the mean time, I can't really tell. It should be fine I guess.

**Comment by markus2330** [comment]
Is this also reflected in the xml? see #46

**Comment by Namoshek** [comment]
It is part of the template that has not really anything to do with the questions.xml. The template consists of several files, so I don't know if we should update it in the repo as well. Basically I only added back the `{PERCENTCOMPLETE}` include tag.

**Comment by markus2330** [comment]
Ok! Lets keep it open for further feedback about the progress bar.

**Comment by sirblackheart** [comment]
relevant feedback:
>  Glaub bei Google Chrome keine Fortschrittsanzeige vorhanden (erst nach dem Test beim oeffnen in Explorer gesehen dass es dort eine gibt, bei Chrome waere mir vorher keine aufgefallen, nachschauen geht halt nach dem Abschließen des Tests nicht)

**Comment by Namoshek** [comment]
I only use Chrome and it is visible there. Maybe (s)he checked it before and after I added it? Please someone else confirm the visibility.

**Comment by markus2330** [comment]
I think its quite obvious that in this case the reason is that it was before/after the progress bar was added.

**Comment by markus2330** [comment]
Someone says it does not matter if the first page displays 20% progress.

**Comment by markus2330** [comment]
Someone else says:

> Ja, aber die scrollen ja auch, von daher würde ich unten anzeigen (also wenn eins durch die Fragen durch ist), wie viele Fragen von allen insgesamt schon durch sind.

**Comment by markus2330** [comment]
Is it possible to have a "To Last Page" instead of "Next" in the How page?

**Comment by Namoshek** [comment]
I don't see a way we could add this feature. The survey works with an HTML-form being submitted on each page. Depending on the button value (`movenext` / `moveprev`), the server knows what to do with the request. As long as we cannot modify the server-side, I don't think we can directly jump to the last page. I also did not find any viable info about this in the www.

**Comment by markus2330** [comment]
I do not want an option to jump from any page to the last page. I only think it would be useful to replace the button's text of the page before the last page (the "How? page).

The rationale is, that then people know that they are nearly finished.

**Comment by Namoshek** [comment]
We could change the button text with JS (I would place the script in the question group description text field). I did that for the experimental survey, but be aware that it will not work for JS disabled (although there is not really a big problem with the button still being name "Next").

I also changed the template so that group descriptions are not displayed anymore (the script made it being displayed without content). If this is a problem, we can change it easily an move the script to another place (e.g. one of the questions), although I don't like that (structure...).

**Comment by sirblackheart** [comment]
I think this is fine to be moved to '625192'

**Comment by Namoshek** [comment]
Added the script to `625192`

**Comment by sirblackheart** [comment]
Looks good to me.

**Comment by markus2330** [comment]
Is fine now!
