### ISSUE TITLE
getenv questions inconsistent with rest

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#5]

**Comment by Namoshek** [comment]
We are still using two answers consisting of full sentences and only phrases for the others, that doesn't look consistent. If you think it's ok, close the issue, I can live with it, just wanted to point it out.

**Comment by markus2330** [comment]
you are right, the problem is that it is an question asking multiple (nearly unrelated) questions.
I will think about it.

**Comment by markus2330** [comment]
getenv "I do not use it (use other to write why)" blocks "other"

**Comment by markus2330** [comment]
I updated it in 978550d9e6cbb8c72dd963c809f48df5d00d2428
It should be now much more consistent.

please also fix the blocking of "other"

**Comment by Namoshek** [comment]
Please see my note in the commit. I changed it to what I think is meant. I also removed the exclusive answer feature so that other can always be filled, but that also means that "I do not" does not disable the other answers anymore.

**Comment by markus2330** [comment]
looks ok, you can close it
