### ISSUE TITLE
Feedback: unclear difference "had contact with" and "used in source code"

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#55]
> Der Unterschied zwischen "had contact with" und "used in source code" bei der Frage "Which configuration systems/libraries/APIs have you already used or would like to use in one of your projects?" ist mir nicht ganz klar. Ich hab das "had contact with" so interpretiert, dass ich bei der BENUTZUNG mal damit zu tun hatte und nicht beim entwickeln.

**Comment by markus2330** [comment]
Interpretation ist eigentlich richtig, d.h. eigentlich nichts zu tun?
