### ISSUE TITLE
Feedback: "You want to configure a FLOSS application. How important are the following ways for you?" 

### ISSUE THREAD

**Issue by sirblackheart** [sirblackheart/elektrasurvey#58]
>  "You want to configure a FLOSS application. How important are the following ways for you?" - Etwas schwer zu sagen, entspricht bisschen einem Ranking was einem lieber ist, wenn aber die Sachen die man bevorzugen würde nicht vorhanden sind dann wären die anderen Optionen trotzdem "very important" damit es irgendeine Möglichkeit gibt zum konfigurieren.

**Comment by markus2330** [comment]
Is it really a problem? Should I ask about specifics here?

**Comment by sirblackheart** [comment]
I put it here so we can reevaluate the situation, but we probably should not change it. I mean the feedbacks objection is basically what we want to read from the scale ranking. If someone rates something low then the would not that much objection if it is missing. If he ranks it high we would probably miss it.

Maybe add another hint:
If you have trouble rating the importance, think about which one you would miss most = more important and which one you could live without = less important.

**Comment by sirblackheart** [comment]
What do you think about extending the existing hint the following way.

> Note: Think about the application(s) your mentioned you work on and think about which ways you would miss most = more important and which one you could live without = less important.

**Comment by markus2330** [comment]
I think people have an intuitive feeling what "important" means for them. They automatically make it relative to the available options. If possible we should avoid making the hint longer.

**Comment by sirblackheart** [comment]
Ok then I close this as wontfix
