### ISSUE TITLE
Overlap in MC Questions

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#60]
![near_overlap_mc.png](near_overlap_mc.png)
![overlap_mc1.png](overlap_mc1.png)
![overlap_mc1](https://cloud.githubusercontent.com/assets/7949075/15798326/dcbc570a-2a34-11e6-8946-d8521f97d331.png)

**Comment by sirblackheart** [comment]
Only one picture works. This sounds like the resize issue.

**Comment by Namoshek** [comment]
How to reproduce? (browser, resolution, ...)

**Comment by markus2330** [comment]
Firefox 1920x1200

It could be a font issue, do you have exactly the same font?

**Comment by Namoshek** [comment]
Font weight looks more bold on your image than on my screen. Font being used is `font-family: "Lato", "Helvetica Neue", Helvetica, Arial, sans-serif;`. Is it possible that some imports are blocked by your browser?

**Comment by markus2330** [comment]
Only different domains would be blocked (only the images, see #27). Its possible that I have some untypical Helvetica installed.

**Comment by Namoshek** [comment]
Don't think we had any further report(s) for this?

**Comment by markus2330** [comment]
Ok, then lets close it.
