### ISSUE TITLE
Filter click-through responses

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#61]
In the statistics, the "No answer" is winning everywhere, is there some simple way to filter responses that provide nearly no answer?

**Comment by Namoshek** [comment]
I had a look two days ago (sorry, forgot to respond), but I don't really see an easy way to filter it. Maybe in the expert settings is some hidden feature for it (where you can select "> 80% filled out" e.g.), but as I said, I had no luck finding it yet.

**Comment by markus2330** [comment]
Ok, maybe @sirblackheart finds something, otherwise we will do it with an external script.

**Comment by Namoshek** [comment]
In the scripts I wrote there is one that filters out answers that have only NA selected (that are click-throughs). And also for the discrete evaluation scripts we have additional filters for NAs. I think that this issue is solved / work-in-progress.
