### ISSUE TITLE
Libreoffice should not be a different choice

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#64]
Libreoffice is part of SPI, and should not be a separate choice additionally

Next to LimeSurvey we should write something like (made this survey possible) and/or (kindly hosts this survey)

**Comment by sirblackheart** [comment]
done

**Comment by markus2330** [comment]
Please keep open for review.

**Comment by Namoshek** [comment]
`LibreOffice` is written in camel-case, so I updated all occurences (welcome page, email-question text and sponsorto answer text). 
I also changed the "LimeSurvey (LimeService, kindly hosting this survey)" part of the email-question text and the sponsorto answer text (altered it a bit for the first and added it for the latter). Please review.

**Comment by sirblackheart** [comment]
Looks good to me? @markus2330 what do you think about the way of presenting the possible donations as list? I also did not mention that i switched to ` SPI, General Donation (0 A.D., LibreOffice, Debian, ArchLinux, …)` instead of the other way around.

In this case i would also kindly as to use the correct "…" unicode instead of other variations for consistency. I already tried to replace most of them, but maybe i overlooked some.

**Comment by markus2330** [comment]
Which kind of list do you mean? Do the links work with the list?

**Comment by sirblackheart** [comment]
inline
![screenshot from 2016-06-06 21-26-40](https://cloud.githubusercontent.com/assets/1131371/15834779/6996d7f0-2c2d-11e6-93b5-05c17cf4de1a.png)
unordered list
![screenshot from 2016-06-06 21-25-04](https://cloud.githubusercontent.com/assets/1131371/15834789/71d60f08-2c2d-11e6-843c-f03c21cfccb9.png)

**Comment by markus2330** [comment]
I dont know why we would need the list twice on the same page. Do you mean you want the inline list on the front page?

Overall I am not sure what your proposal is, can you add this to experimental?

**Comment by markus2330** [comment]
Btw. we should not hijack issues that are already ready for review for different issues.

**Comment by sirblackheart** [comment]
> Btw. we should not hijack issues that are already ready for review for different issues.

I made this change when changing things for this issue but we can switch over to #42 if you want. What i say is i already put the unordered list in all occurrences. Just take a look at the current not pilot survey...

> Overall I am not sure what your proposal is, can you add this to experimental?
it is in the non experimental for quite some time

**Comment by markus2330** [comment]
I think the list is great, but it should be in the front page of the survey! One just have to type a single letter into the e-mail address field and immediately see the list. I see no reason to have the list twice on the same page.

**Comment by sirblackheart** [comment]
I switched back to inline list for the email field, but i suggest we still keep the donation info there as a reminder to fill out the email field. The difference of the link color in contrast with the rest of the text could encourage people to actually read the text.

**Comment by markus2330** [comment]
Ok, you have a good point. Nevertheless we should also be transparent about the donation on the front page.

**Comment by sirblackheart** [comment]
> Ok, you have a good point. Nevertheless we should also be transparent about the donation on the front page.
Yes it makes sense to have the information at both locations.

**Comment by omnidan** [comment]
I reviewed all changes. Should we mention LibreOffice again at the end? (Maybe some people forgot what SPI is?)

**Comment by sirblackheart** [comment]
> Should we mention LibreOffice again at the end? (Maybe some people forgot what SPI is?)
Yes i updated the three occurrences of the list and they should now be more consistent.

**Comment by markus2330** [comment]
See #74
