### ISSUE TITLE
Fix JS scripts for the final survey

### ISSUE THREAD

**Issue by Namoshek** [sirblackheart/elektrasurvey#65]
Some JS scripts require the correct HTML question/answer IDs to work, this has to be fixed. Example: flossprojects-question.

**Comment by Namoshek** [comment]
Fixed the script in the flossprojects question. Did we have other scripts somewhere else? I didn't miss any when looking through the survey quite quickly, but maybe I'm just blind by now.

**Comment by sirblackheart** [comment]
Not that i am aware off. Looks fine to me, add project works as expected.

**Comment by markus2330** [comment]
@Namoshek should close this.

**Comment by markus2330** [comment]
There is also a "!!!important update to real link on activation" in the final page, do need a ticket for this, too?

**Comment by sirblackheart** [comment]
That should be #51

**Comment by Namoshek** [comment]
I think the scripts are updated, for the other point, see #51.
