### ISSUE TITLE
Configuration specification

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#66]
Add answer if external projects are relevant, e.g.

- for external tools accessing configuration

**Comment by sirblackheart** [comment]
added, please review

**Comment by Namoshek** [comment]
Where did you add it? I can't find it for the question `specifyconfig`, which seems to be meant.

**Comment by sirblackheart** [comment]
You are right i put i accidentally put it in `effortconfexp`, fixed it.

**Comment by sirblackheart** [comment]
nicely done

**Comment by markus2330** [comment]
Thank you, well done!
