### ISSUE TITLE
add text fields

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#68]
People should be able to add additional text fields for

1. the question "Which configuration systems/libraries/APIs" (next to XSettings,..; ideally with smileys in the follow up)
2. the last question (Finally, which benefits do you think are essential in order to add..)

**Comment by sirblackheart** [comment]
@markus2330 please take a look at the proposed implementation for this in 'experiments'
as @Namoshek already stated this is the only "fast" (~2h) way to solve this and we could at least have one text field for other

**Comment by markus2330** [comment]
Yes, I am very happy with this solution. Thank you! (even though more than one new item might be better.)

Textual fixes:
Other: (you can name other after making a selection) 					
->
(Please name it after making a selection)

Please name the application you hade in mind for other in the previous question.
-> (2 changes!, *had*)
Please name the configuration systems/libraries/APIs you had in mind for your additional choice in the previous question.

You can add it to the final version.

**Comment by sirblackheart** [comment]
Yes that sound much better.

I also switched from` Other: `to `other:` for consistency
and adapted it for the last question:

> Please name the benefits you had in mind for your additional choice in the previous question.

**Comment by omnidan** [comment]
Nice solution :+1: The texts seem fine now and `other:` is consistent too.

**Comment by markus2330** [comment]
I also like the solution, but there is a small problem as reported in #81
