### ISSUE TITLE
sponsorto text part in intro

### ISSUE THREAD

**Issue by Namoshek** [sirblackheart/elektrasurvey#69]
I'm not happy with the following part of the intro
> For every thoroughly and not anonymous finished survey € 40 cent will be sponsored to one organisation of your choice of the following:

First, it should be `anonymously` in my opinion and secondly, the hinder part should probably be swapped in some way, although I'm not sure what is the correct one... (`€ 40 cent will be donated to one of the following organizations of your choice`). I also replaced `sponsored` by `donated`, because I think that the initial is rather used for "being sponsored" and not for giving money away.

Result:
> For every thoroughly and not anonymously finished survey € 40 cent will be donated to one of the following organizations of your choice:

**Comment by markus2330** [comment]
Thank you, nice improvement!

Btw. I am considering to increase the € 40 cent, but to limit the maximum amount spend (400 €). Would this change encourage people?

**Comment by Namoshek** [comment]
I think that is hard to tell. It is possible that some people will think "if he will give away only 400€ and the limit is reached, filling out the survey has no benefit anymore...". I doubt that this is the case, but somehow I feel better if we do not give an upper limit, but rather a lower one (the 200€ like now).

**Comment by sirblackheart** [comment]
Updated in `625192` intro text and summary of the question with id `email`
please review

**Comment by Namoshek** [comment]
Looks good!

**Comment by markus2330** [comment]
Ok, then lets stay with € 40 cent. Thank you for fixing the text!
