### ISSUE TITLE
Inconsistencies in " To which organisation..."

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#74]
- [x] inconsistent "40 €cent" (should be € 40 cent)
- [x] Mozilla/Firefox vs. Wikipedia/Wikimedia Foundation: company or product first?
- [x] Sometimes uses /, sometimes () to separate
- [x] no link to LimeService
- [x] inconsistency with text on start page, e.g.: "LimeSurvey (LimeService, kindly hosting this survey)" vs. "LimeSurvey (kindly hosts this survey)"

**Comment by sirblackheart** [comment]
>  inconsistent "40 €cent" (should be € 40 cent)

next time please add the location, thank you. updated in `sponsorto` text

> Mozilla/Firefox vs. Wikipedia/Wikimedia Foundation: company or product first?

changed this to foundation first.

 > Sometimes uses /, sometimes () to separate

Again where exactly and what do you mean here? If i have to guess what you meant the probability is high to make the wrong changes.

> no link to LimeService

added everywhere

> inconsistency with text on start page, e.g.: "LimeSurvey (LimeService, kindly hosting this survey)" vs. "LimeSurvey (kindly hosts this survey)"

changed to `LimeSurvey (LimeService, kindly hosting this survey)`

I hope i got everything, but my concentration is really lacking from the long work hours on the survey.

**Comment by markus2330** [comment]
In the title I wrote the beginning of the question the tasks refer to. How do you want the location to be given?

> Sometimes uses /, sometimes () to separate

Its a minor problem but we could easily avoid the usage of / and instead always have the same syntax:

foundation (examples+projects+notes)

**Comment by sirblackheart** [comment]
> In the title I wrote the beginning of the question the tasks refer to. How do you want the location to be given?

Ah sorry, like i said. Lack of concentration.

> Its a minor problem but we could easily avoid the usage of / and instead always have the same syntax:
> foundation (examples+projects+notes)

Ah, it seems we had the same idea, I already changed it while fixing `company or product first?` so i was at loss when looking for any /.

**Comment by markus2330** [comment]
Thank you! And please take a break from fixing survey issues!

**Comment by omnidan** [comment]
There was still an inconsistency that I fixed:

* Start page: LimeSurvey (LimeService kindly hosts this survey)
* Last page: LimeSurvey (LimeService, kindly hosting this survey)

I changed the second one to `hosts`.

**Comment by markus2330** [comment]
There is still one more place saying "kindly hosting this survey)" in "To which organisation should.."

and at the frontpage, there is a comma missing: "(LimeService kindly hosts this survey)"

**Comment by markus2330** [comment]
another inconsistency:
SPI, General Donation (0 A.D., LibreOffice, Debian, ArchLinux, …)
SPI General Donation

maybe we should go for
SPI (General Donation: 0 A.D., LibreOffice, Debian, ArchLinux, …)

**Comment by sirblackheart** [comment]
> SPI (General Donation: 0 A.D., LibreOffice, Debian, ArchLinux, …)

switched to this one

i hope i got now all of them.

**Comment by markus2330** [comment]
did you also change the LimeService comma inconsistency?

**Comment by sirblackheart** [comment]
yes

**Comment by markus2330** [comment]
@omnidan can you review again?

**Comment by omnidan** [comment]
Looks good now :+1:

**Comment by markus2330** [comment]
Thank you!
