### ISSUE TITLE
Color of previous button

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#76]
Der "Previous"-Button sollte meiner Meinung nach nicht Grau sein. Sieht so aus, als waere das zurueck gehen nicht moeglich.

**Comment by sirblackheart** [comment]
Persönlich hätte ich den jetzt nicht als grau empfunden. Zusätzlich ist es inzwischen typisch den typischen Pfad in Dialogen nach vorn grafisch hervorzuheben. Auch der `:hover` Effekt macht ihn eigentlich als bedienbar erkenntlich.

Vielleicht sollten wir ihn nur um eine Spur mehr einfärben.

**Comment by markus2330** [comment]
Ja, ich denke auch da geht es nur um Nuancen. Er schaut zwar nicht grau aus, aber verglichen mit "Next" wirkt er schon "inaktiv".

**Comment by sirblackheart** [comment]
The back button should have now s slightly stronger color tone. Please review.

**Comment by markus2330** [comment]
@omnidan can you look through all "needs review in lime survey" and also fix some issues in limesurvey?

**Comment by omnidan** [comment]
Looks exactly the same as in the pilot to me, but in neither cases it looks gray or "non-clickable". I assume this has been changed in both surveys?

![https://i.imgur.com/6PA9uFW.png](https://i.imgur.com/6PA9uFW.png)

**Comment by Namoshek** [comment]
Template changes always affect all surveys using the template, including active ones.

**Comment by markus2330** [comment]
Thanks, should be fixed then!
