### ISSUE TITLE
Make promises realistic

### ISSUE THREAD

**Issue by markus2330** [sirblackheart/elektrasurvey#82]
I am afraid this is impossible (at last page):

"Additionally we will post a link on the mailing list or site that got you here."

We'll never know who reposted it where and how the people reached us. Also we have no control over news that might mention us once but not for our results.

**Comment by sirblackheart** [comment]
Ok, I deleted the part.

**Comment by markus2330** [comment]
Nevertheless we can have a best effort to notify as many as possible. But I think we do not have to mention this.

**Comment by Namoshek** [comment]
Checked and sentence is gone.
